#############################################################################
# Makefile for building: motor3d
# Generated by qmake (1.07a) (Qt 3.3.4) on: Tue May 15 00:10:54 2007
# Project:  motor3d.pro
# Template: app
# Command: $(QMAKE) -o Makefile motor3d.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = gcc
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/UNIONFS/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = ccaja.h \
		ccamara.h \
		centidad3d.h \
		cframebuffer.h \
		cinterfaz.h \
		clienzo.h \
		cluz.h \
		cmatriz4x4.h \
		cmundo3d.h \
		cobjeto3d.h \
		cpuntofijo.h \
		csuperficierevolucion.h \
		ctriangulo.h \
		cvertice3d.h \
		czbuffer.h \
		mate.h \
		Sup_Revolucion.h
SOURCES = ccaja.cpp \
		ccamara.cpp \
		centidad3d.cpp \
		cframebuffer.cpp \
		cinterfaz.cpp \
		clienzo.cpp \
		cluz.cpp \
		cmatriz4x4.cpp \
		cmundo3d.cpp \
		cobjeto3d.cpp \
		cpuntofijo.cpp \
		csuperficierevolucion.cpp \
		ctriangulo.cpp \
		cvertice3d.cpp \
		czbuffer.cpp \
		motor3d.cpp
OBJECTS = ccaja.o \
		ccamara.o \
		centidad3d.o \
		cframebuffer.o \
		cinterfaz.o \
		clienzo.o \
		cluz.o \
		cmatriz4x4.o \
		cmundo3d.o \
		cobjeto3d.o \
		cpuntofijo.o \
		csuperficierevolucion.o \
		ctriangulo.o \
		cvertice3d.o \
		czbuffer.o \
		motor3d.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_cinterfaz.cpp \
		moc_clienzo.cpp \
		moc_cmundo3d.cpp
OBJMOC = moc_cinterfaz.o \
		moc_clienzo.o \
		moc_cmundo3d.o
DIST	   = motor3d.pro
QMAKE_TARGET = motor3d
DESTDIR  = 
TARGET   = motor3d

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: motor3d.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile motor3d.pro
qmake: 
	@$(QMAKE) -o Makefile motor3d.pro

dist: 
	@mkdir -p .tmp/motor3d && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/motor3d/ && ( cd `dirname .tmp/motor3d` && $(TAR) motor3d.tar motor3d && $(GZIP) motor3d.tar ) && $(MOVE) `dirname .tmp/motor3d`/motor3d.tar.gz . && $(DEL_FILE) -r .tmp/motor3d

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

ccaja.o: ccaja.cpp ccaja.h \
		cvertice3d.h \
		cpuntofijo.h

ccamara.o: ccamara.cpp ccamara.h \
		centidad3d.h \
		cmatriz4x4.h \
		cvertice3d.h \
		cpuntofijo.h \
		mate.h

centidad3d.o: centidad3d.cpp centidad3d.h \
		cvertice3d.h \
		cmatriz4x4.h \
		cpuntofijo.h \
		mate.h

cframebuffer.o: cframebuffer.cpp cframebuffer.h

cinterfaz.o: cinterfaz.cpp cinterfaz.h \
		centidad3d.h \
		clienzo.h \
		cframebuffer.h \
		czbuffer.h \
		cpuntofijo.h \
		cvertice3d.h \
		cmatriz4x4.h \
		mate.h

clienzo.o: clienzo.cpp clienzo.h \
		cmundo3d.h \
		cframebuffer.h \
		czbuffer.h \
		cpuntofijo.h \
		centidad3d.h \
		cinterfaz.h \
		csuperficierevolucion.h \
		ctriangulo.h \
		cvertice3d.h \
		mate.h \
		ccamara.h \
		cmatriz4x4.h \
		cobjeto3d.h

cluz.o: cluz.cpp cluz.h \
		centidad3d.h \
		cvertice3d.h \
		cmatriz4x4.h \
		cpuntofijo.h \
		mate.h

cmatriz4x4.o: cmatriz4x4.cpp cmatriz4x4.h \
		cvertice3d.h \
		cpuntofijo.h \
		mate.h

cmundo3d.o: cmundo3d.cpp cmundo3d.h \
		cinterfaz.h \
		cobjeto3d.h \
		ccamara.h \
		cluz.h \
		cvertice3d.h \
		clienzo.h \
		centidad3d.h \
		cframebuffer.h \
		czbuffer.h \
		csuperficierevolucion.h \
		ctriangulo.h \
		mate.h \
		cpuntofijo.h \
		cmatriz4x4.h

cobjeto3d.o: cobjeto3d.cpp cobjeto3d.h \
		centidad3d.h \
		cvertice3d.h \
		ctriangulo.h \
		mate.h \
		cmatriz4x4.h \
		cpuntofijo.h

cpuntofijo.o: cpuntofijo.cpp cpuntofijo.h

csuperficierevolucion.o: csuperficierevolucion.cpp csuperficierevolucion.h \
		Sup_Revolucion.h \
		cvertice3d.h \
		ctriangulo.h \
		cframebuffer.h \
		cobjeto3d.h \
		cpuntofijo.h \
		mate.h \
		centidad3d.h \
		cmatriz4x4.h

ctriangulo.o: ctriangulo.cpp ctriangulo.h \
		cvertice3d.h \
		mate.h \
		cpuntofijo.h

cvertice3d.o: cvertice3d.cpp cvertice3d.h \
		cmatriz4x4.h \
		ctriangulo.h \
		cpuntofijo.h \
		mate.h

czbuffer.o: czbuffer.cpp czbuffer.h \
		cpuntofijo.h

motor3d.o: motor3d.cpp cmundo3d.h \
		clienzo.h \
		centidad3d.h \
		cframebuffer.h \
		czbuffer.h \
		cinterfaz.h \
		csuperficierevolucion.h \
		ctriangulo.h \
		cvertice3d.h \
		mate.h \
		ccamara.h \
		cpuntofijo.h \
		cmatriz4x4.h \
		cobjeto3d.h

moc_cinterfaz.o: moc_cinterfaz.cpp  cinterfaz.h clienzo.h \
		cframebuffer.h \
		czbuffer.h \
		cpuntofijo.h

moc_clienzo.o: moc_clienzo.cpp  clienzo.h cframebuffer.h \
		czbuffer.h \
		cpuntofijo.h

moc_cmundo3d.o: moc_cmundo3d.cpp  cmundo3d.h clienzo.h \
		centidad3d.h \
		cframebuffer.h \
		czbuffer.h \
		cinterfaz.h \
		csuperficierevolucion.h \
		ctriangulo.h \
		cvertice3d.h \
		mate.h \
		ccamara.h \
		cpuntofijo.h \
		cmatriz4x4.h \
		cobjeto3d.h

moc_cinterfaz.cpp: $(MOC) cinterfaz.h
	$(MOC) cinterfaz.h -o moc_cinterfaz.cpp

moc_clienzo.cpp: $(MOC) clienzo.h
	$(MOC) clienzo.h -o moc_clienzo.cpp

moc_cmundo3d.cpp: $(MOC) cmundo3d.h
	$(MOC) cmundo3d.h -o moc_cmundo3d.cpp

####### Install

install:  

uninstall:  

